### ISSUE TITLE
XSOM Parser unable to parse wsdl with element <s:element ref="s:schema"/>

### ISSUE THREAD

**Issue by Syed-SnapLogic** [dswarm/xsom#1]
Hi,
  There is a WSDL as follows:

 `<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://tempuri.org/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <s:import namespace="http://www.w3.org/2001/XMLSchema" />
      <s:element name="MessageText">
        <s:complexType />
      </s:element>
      <s:element name="MessageTextResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="MessageTextResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="HelloTable">
        <s:complexType />
      </s:element>
      <s:element name="HelloTableResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="HelloTableResult">
              <s:complexType>
                <s:sequence>
                  <s:element ref="s:schema" />
                  <s:any />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="HelloTable2">
        <s:complexType />
      </s:element>
      <s:element name="HelloTable2Response">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="HelloTable2Result">
              <s:complexType>
                <s:sequence>
                  <s:element ref="s:schema" />
                  <s:any />
                </s:sequence>
              </s:complexType>
            </s:element>
            <s:element minOccurs="0" maxOccurs="1" name="ID" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="MessageTextSoapIn">
    <wsdl:part name="parameters" element="tns:MessageText" />
  </wsdl:message>
  <wsdl:message name="MessageTextSoapOut">
    <wsdl:part name="parameters" element="tns:MessageTextResponse" />
  </wsdl:message>
  <wsdl:message name="HelloTableSoapIn">
    <wsdl:part name="parameters" element="tns:HelloTable" />
  </wsdl:message>
  <wsdl:message name="HelloTableSoapOut">
    <wsdl:part name="parameters" element="tns:HelloTableResponse" />
  </wsdl:message>
  <wsdl:message name="HelloTable2SoapIn">
    <wsdl:part name="parameters" element="tns:HelloTable2" />
  </wsdl:message>
  <wsdl:message name="HelloTable2SoapOut">
    <wsdl:part name="parameters" element="tns:HelloTable2Response" />
  </wsdl:message>
  <wsdl:portType name="TestServiceSoap">
    <wsdl:operation name="MessageText">
      <wsdl:input message="tns:MessageTextSoapIn" />
      <wsdl:output message="tns:MessageTextSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="HelloTable">
      <wsdl:input message="tns:HelloTableSoapIn" />
      <wsdl:output message="tns:HelloTableSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="HelloTable2">
      <wsdl:input message="tns:HelloTable2SoapIn" />
      <wsdl:output message="tns:HelloTable2SoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="TestServiceSoap" type="tns:TestServiceSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
    <wsdl:operation name="MessageText">
      <soap:operation soapAction="http://tempuri.org/MessageText" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="HelloTable">
      <soap:operation soapAction="http://tempuri.org/HelloTable" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="HelloTable2">
      <soap:operation soapAction="http://tempuri.org/HelloTable2" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TestService">
    <documentation xmlns="http://schemas.xmlsoap.org/wsdl/" />
    <wsdl:port name="TestServiceSoap" binding="tns:TestServiceSoap">
      <soap:address location="http://bcc-meridio.uprava.ina.hr/saptest/testservice.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>`

If we look at the schema definition, there is an element declaration as follows:
`<s:element ref="s:schema"/>
 <s:any'>`

XSOM parser is unable to parse such schemas.  To make the problem more simpler, there is an xsd file as follows:
`<?xml version="1.0" encoding="utf-8"?>
<s:schema xmlns:s="http://www.w3.org/2001/XMLSchema">
 <s:element name="name" s:type="s:string"/>
 <s:element name="id" s:type="s:int"/>
 <s:element name="mananger">
    <s:complexType>
       <s:sequence>
         <s:element ref="s:schema"/>
       </s:sequence>
    </s:complexType>
 </s:element>
</s:schema>`

XSOM parser is unable to generate result after parsing the above schema.

Is there any workaround to make XSOM parser able to return the result?  Or is it a bug that you guys need to fix?  Please let me know ASAP as I am using XSOM parser in my projects and need to kick out this issue.

**Comment by boferri** [comment]
Hi @Syed-SnapLogic,

I'm sorry, but we do not really maintain the xsom library. We just did a fork of it from the old SVN repository (which does not seem to be available anymore, i.e., the [xsom project seem to be archived](https://javaee.github.io/other-migrated-projects.html)). You may contact the discussion list at glassfish at javaee dot groups dot io for your issue. You can also fork our fork here at GitHub and try to create a fix on your own.

Cheers,


Bo
